/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AddressType } from "./addresstype";
import { Expose } from "class-transformer";

export class Addresses extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "address_type" })
  addressType: AddressType;

  @SpeakeasyMetadata()
  @Expose({ name: "city" })
  city: string;

  @SpeakeasyMetadata()
  @Expose({ name: "country" })
  country: string;

  @SpeakeasyMetadata()
  @Expose({ name: "postal_code" })
  postalCode: string;

  @SpeakeasyMetadata()
  @Expose({ name: "state" })
  state: string;

  @SpeakeasyMetadata()
  @Expose({ name: "street1" })
  street1: string;

  @SpeakeasyMetadata()
  @Expose({ name: "street2" })
  street2: string;
}
