/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum AddressTypeEnum {
  Primary = "primary",
  Mailing = "mailing",
  Other = "other",
  Billing = "billing",
  Shipping = "shipping",
}
