/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum EmailAddressesEmailAddressTypeEnum {
  Primary = "primary",
  Work = "work",
}

export class EmailAddresses extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "email_address" })
  emailAddress: string;

  @SpeakeasyMetadata()
  @Expose({ name: "email_address_type" })
  emailAddressType: EmailAddressesEmailAddressTypeEnum;
}
