/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class ErrorsSource extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "pointer" })
    pointer?: string;
}

export class Errors extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "detail" })
    detail?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "problem_type" })
    problemType?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "source" })
    @Type(() => ErrorsSource)
    source?: ErrorsSource;

    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title?: string;
}
