/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class LogsLogSummary extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "method" })
  method?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "status_code" })
  statusCode?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "url" })
  url?: string;
}

export class Logs extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "dashboard_view" })
  dashboardView?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "log_id" })
  logId?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "log_summary" })
  @Type(() => LogsLogSummary)
  logSummary?: LogsLogSummary;
}
