/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PhoneNumberTypeEnum } from "./phonenumbertypeenum";
import { Expose } from "class-transformer";

export class PhoneNumbers extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "phone_number" })
  phoneNumber: string;

  @SpeakeasyMetadata()
  @Expose({ name: "phone_number_type" })
  phoneNumberType: PhoneNumberTypeEnum;
}
