/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetLeadPathParams extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=lead_id",
  })
  leadId: string;
}

export class GetLeadQueryParams extends SpeakeasyBase {
  /**
   * Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=expand",
  })
  expand?: string;
}

export class GetLeadHeaders extends SpeakeasyBase {
  /**
   * The customer ID that uniquely identifies the customer in your application
   */
  @SpeakeasyMetadata({
    data: "header, style=simple;explode=false;name=x-customer-id",
  })
  xCustomerId: string;

  /**
   * The provider name
   */
  @SpeakeasyMetadata({
    data: "header, style=simple;explode=false;name=x-provider-name",
  })
  xProviderName: string;
}

export class GetLeadRequest extends SpeakeasyBase {
  @SpeakeasyMetadata()
  pathParams: GetLeadPathParams;

  @SpeakeasyMetadata()
  queryParams: GetLeadQueryParams;

  @SpeakeasyMetadata()
  headers: GetLeadHeaders;
}

export class GetLeadResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Lead
   */
  @SpeakeasyMetadata()
  lead?: shared.Lead;
}
